"""
Django settings for encore project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import zoneinfo
from pathlib import Path
from typing import Optional

from pydantic_settings import BaseSettings


class CoreSettings(BaseSettings):
    """Core Settings class
    Will use values from env variables else the default values.
    """

    DEBUG_APP: bool = False

    ENVIRONMENT: str = "dev"
    ALLOWED_HOSTS: str = "localhost"  # comma seperated string
    STATIC_ROOT: Optional[str] = None

    USE_POSTGRES: bool = True
    PG_DB_NAME: str = "encore"
    PG_DB_USER: str = "correlator"
    PG_DB_PWD: str = "correlator"
    PG_DB_HOST: str = "pgdb"
    PG_DB_PORT: str = "5432"

    # SECURITY WARNING: keep the secret key used in production secret!
    ENCORE_SECRET_KEY: str = "django-insecure-2b8i!u14e$=+mzbmy^!^^8_#6g_@(5%_1)w3+g8xkhw3m=_tz8"


core_settings = CoreSettings()
ENVIRONMENT = core_settings.ENVIRONMENT.lower()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = core_settings.ENCORE_SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = core_settings.DEBUG_APP

ALLOWED_HOSTS = core_settings.ALLOWED_HOSTS.split(",")


# Application definition

INSTALLED_APPS = [
    "correlator.apps.CorrelatorAdminConfig",  # "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sites",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "django_celery_beat",
    # "django_filters",
    "launchpad",
    "elastic",
    "snmp",
    "glpi",
]

if core_settings.USE_POSTGRES:
    INSTALLED_APPS.append("django.contrib.postgres")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "correlator.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "correlator.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

IST_TZ = zoneinfo.ZoneInfo("Asia/Kolkata")

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = core_settings.STATIC_ROOT or BASE_DIR.parent.parent.joinpath("static")

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# DB
if core_settings.USE_POSTGRES:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": core_settings.PG_DB_NAME,
            "USER": core_settings.PG_DB_USER,
            "PASSWORD": core_settings.PG_DB_PWD,
            "HOST": core_settings.PG_DB_HOST,
            "PORT": core_settings.PG_DB_PORT,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
